# -*- coding: utf-8 -*-
"""movie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tvrlk4Qt3bkXrgBFvpMIeFcfEHH-cFLr
"""

import streamlit as st
import pandas as pd
import numpy as np

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="Movie Recommender", page_icon="🍿", layout="wide")

# --- DATA LOADING & CACHING ---
# We cache the data so it doesn't reload every time the user clicks a button
@st.cache_data
def load_and_prep_data():
    # 1. Load the ratings data
    column_names = ['user_id', 'item_id', 'rating', 'timestamp']
    df = pd.read_csv('ml-100k/u.data', sep='\t', names=column_names)

    # 2. Load the movie titles (u.item is pipe-separated and needs latin-1 encoding)
    movie_cols = ['item_id', 'title']
    movies = pd.read_csv('ml-100k/u.item', sep='|', encoding='latin-1', header=None, usecols=[0, 1], names=movie_cols)

    # 3. Merge them together
    merged_df = pd.merge(df, movies, on='item_id')

    # 4. Create a pivot table (Users as rows, Movies as columns, Ratings as values)
    movie_matrix = merged_df.pivot_table(index='user_id', columns='title', values='rating')

    # 5. Get the total number of ratings for each movie to filter out unpopular ones
    ratings_count = pd.DataFrame(merged_df.groupby('title')['rating'].count())
    ratings_count.rename(columns={'rating': 'num_of_ratings'}, inplace=True)

    return movie_matrix, ratings_count, movies['title'].sort_values().unique()

# Load the data
movie_matrix, ratings_count, movie_list = load_and_prep_data()

# --- RECOMMENDER FUNCTION ---
def get_recommendations(movie_name, min_reviews=50):
    # Get user ratings for the selected movie
    user_movie_rating = movie_matrix[movie_name]

    # Calculate correlation of this movie with all other movies
    similar_movies = movie_matrix.corrwith(user_movie_rating)

    # Create a dataframe from the results
    corr_movie = pd.DataFrame(similar_movies, columns=['Correlation'])
    corr_movie.dropna(inplace=True) # Remove NaN values

    # Join with the ratings count
    corr_movie = corr_movie.join(ratings_count['num_of_ratings'])

    # Filter out movies with too few reviews and sort by highest correlation
    recommendations = corr_movie[corr_movie['num_of_ratings'] > min_reviews].sort_values('Correlation', ascending=False)

    # Return top 5 (skipping the first one, which is the movie itself)
    return recommendations.iloc[1:6]

# --- USER INTERFACE ---
st.title("🍿 Group Movie Recommender System")
st.markdown("### Powered by Item-Based Collaborative Filtering")

st.write("Select a movie you enjoyed, and our algorithm will recommend 5 similar movies based on community rating patterns.")

# Dropdown menu for movie selection
selected_movie = st.selectbox("Choose a movie:", movie_list)

# Generate Button
if st.button("Get Recommendations"):
    with st.spinner('Calculating correlations...'):
        try:
            recs = get_recommendations(selected_movie)

            st.success("Here are your top 5 recommendations:")

            # Display results neatly
            for index, row in recs.iterrows():
                # Streamlit metric card for nice formatting
                st.metric(label=f"🎬 {index}", value=f"{row['Correlation']*100:.1f}% Match", delta=f"{int(row['num_of_ratings'])} community reviews")
                st.divider()

        except Exception as e:
            st.error(f"Not enough data to find correlations for this specific movie. Please try a more popular title. (Error: {e})")